### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by gpestana** [gpestana/rdoc#13]
Create examples to show how the CRDT interface works.

**Comment by gedw99** [comment]
Will be amazing to see. Glad this is still going forward. I am planning to use this with flutter for mobile apps to allow offline editing.

**Comment by gedw99** [comment]
https://medium.com/@germansaprykin/opengl-with-texture-widget-f919743d25d9

**Comment by gedw99** [comment]
I just realised that the quill document standard is based on OT ! It's also pretty simple.

Thinking it would be a great example.

Check this out !
https://github.com/fmpwizard/go-quilljs-delta

**Comment by gpestana** [comment]
@gedw99 looks really nice, definitely will take some ideas from there. If you want to check how the low level interface with the JSON document will look like, you can check the first end to end test which uses examples from the [original paper](https://arxiv.org/abs/1608.03960) here: https://github.com/gpestana/rdoc/blob/master/e2e_test.go

The current interface is still quite verbose (operations and all its components have to be defined manually) but this low-level interface is meant to be used by a user API which will automatically generate and apply the operations based on an high level JSON API. 

I will keep adding the e2e tests and create the examples from there!
