### ISSUE TITLE
Have you seen RON?

### ISSUE THREAD

**Issue by volyx** [gpestana/rdoc#22]
https://github.com/gritzko/ron, maybe it will be usefull

**Comment by gpestana** [comment]
hey @volyx! no I haven't., it looks cool though. it seems it comes with more features than just the data structure, is that right? (e.g. there's the swarm layer too)

**Comment by volyx** [comment]
Yes, RON is just protocol and data structures. Swarm - network, storage, auth.(layer on top of it)

**Comment by gpestana** [comment]
yep, it looks pretty cool. got to check it out with time. rdoc is basically just the barebones of a JSON CRDT. the networking and interaction protocol is left to the user.
