### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by gedw99** [gpestana/rdoc#7]
This looks really interesting. It's great to see crdt being attempted.

It looks like an OT based crdt. I was wondering what is the current status. For example has a test harness been developed yet to prove that all instance types eventually become consistent over time ? 

Thanks for this great work. I hope I can help move it along.

**Comment by gpestana** [comment]
hey @gedw99 thanks! yep, OT based CRDT and the status is not ready yet, but working on it 😄 I'm now finishing the internals documentation with new implementation details which will require some refactoring. How about I'll ask you for feedback once the documentation is committed?

**Comment by gedw99** [comment]
Perfect !!

**Comment by gpestana** [comment]
This [PR-8](https://github.com/gpestana/rdoc/pull/8) is adding the specs and implementation details for the library. Feel free to comment/suggest anything 👌

**Comment by gpestana** [comment]
@gedw99 I will close this issue and will add examples later on once the API is stable and there is a minimal subset for testing the library.
